export const columnsContract = {
  columns: {
    auto: 'auto',
    1: '1',
    2: '2',
    3: '3',
    4: '4',
    5: '5',
    6: '6',
    7: '7',
    8: '8',
    9: '9',
    10: '10',
    11: '11',
    12: '12',
    '3xs': 'var(--container-3xs)',
    '2xs': 'var(--container-2xs)',
    xs: 'var(--container-xs)',
    sm: 'var(--container-sm)',
    md: 'var(--container-md)',
    lg: 'var(--container-lg)',
    xl: 'var(--container-xl)',
    '2xl': 'var(--container-2xl)',
    '3xl': 'var(--container-3xl)',
    '4xl': 'var(--container-4xl)',
    '5xl': 'var(--container-5xl)',
    '6xl': 'var(--container-6xl)',
    '7xl': 'var(--container-7xl)',
  },
} as const;
