export const interactivityContract = {
  appearance: {
    none: 'none',
    auto: 'auto',
  },
  cursor: {
    auto: 'auto',
    default: 'default',
    pointer: 'pointer',
    wait: 'wait',
    text: 'text',
    move: 'move',
    help: 'help',
    'not-allowed': 'not-allowed',
    none: 'none',
    'context-menu': 'context-menu',
    progress: 'progress',
    cell: 'cell',
    crosshair: 'crosshair',
    'vertical-text': 'vertical-text',
    alias: 'alias',
    copy: 'copy',
    'no-drop': 'no-drop',
    grab: 'grab',
    grabbing: 'grabbing',
    'all-scroll': 'all-scroll',
    'col-resize': 'col-resize',
    'row-resize': 'row-resize',
    'n-resize': 'n-resize',
    'e-resize': 'e-resize',
    's-resize': 's-resize',
    'w-resize': 'w-resize',
    'ne-resize': 'ne-resize',
    'nw-resize': 'nw-resize',
    'se-resize': 'se-resize',
    'sw-resize': 'sw-resize',
    'ew-resize': 'ew-resize',
    'ns-resize': 'ns-resize',
    'nesw-resize': 'nesw-resize',
    'nwse-resize': 'nwse-resize',
    'zoom-in': 'zoom-in',
    'zoom-out': 'zoom-out',
  },
  pointerEvents: {
    none: 'none',
    auto: 'auto',
  },
  resize: {
    none: 'none',
    y: 'vertical',
    x: 'horizontal',
    DEFAULT: 'both',
  },
  scrollBehavior: {
    auto: 'auto',
    smooth: 'smooth',
  },
  scrollSnapAlign: {
    start: 'start',
    end: 'end',
    center: 'center',
    none: 'none',
  },
  scrollSnapStop: {
    normal: 'normal',
    always: 'always',
  },
  scrollSnapType: {
    none: 'none',
    x: 'x var(--tw-scroll-snap-strictness)',
    y: 'y var(--tw-scroll-snap-strictness)',
    both: 'both var(--tw-scroll-snap-strictness)',
    mandatory: 'mandatory',
    proximity: 'proximity',
  },
  touchAction: {
    auto: 'auto',
    none: 'none',
    'pan-x': 'pan-x',
    'pan-left': 'pan-left',
    'pan-right': 'pan-right',
    'pan-y': 'pan-y',
    'pan-up': 'pan-up',
    'pan-down': 'pan-down',
    'pinch-zoom': 'pinch-zoom',
    manipulation: 'manipulation',
  },
  userSelect: {
    none: 'none',
    text: 'text',
    all: 'all',
    auto: 'auto',
  },
  willChange: {
    auto: 'auto',
    scroll: 'scroll-position',
    contents: 'contents',
    transform: 'transform',
  },
} as const;
